# Image of workspace. Learn more: https://www.gitpod.io/docs/configure/workspaces/workspace-image
image: gitpod/workspace-postgres:2024-01-17-14-14-06

# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name : postgreSQL
    command: | 
      pg_start
  - name : redis
    openMode: tab-after
    before: | 
      sudo apt-get update && sudo apt-get install -y redis-server && sudo rm -rf /var/lib/apt/lists/*
    command: | 
      redis-server
  - name: server
    openMode: tab-after
    before: |
      cd ./server
    init: |
      yarn install
    command: |
      yarn start
  - name: frontend
    openMode: tab-after
    before: |
      cd ./client
    init: |
      pnpm install
    command: |
      pnpm dev

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
    - name: server
      description: MedusaJS Admin GUI
      port: 9000
      onOpen: open-browser
      visibility: public
    - name: client
      description: Customer Website
      port: 5173
      onOpen: open-browser
      visibility: public

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart