# Image of workspace. Learn more: https://www.gitpod.io/docs/configure/workspaces/workspace-image
image: gitpod/workspace-postgres:2024-01-17-14-14-06

# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: Startup
    init: pg_start

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart